#!/bin/bash
# Exit immediately if a command exits with a non-zero status
set -e

# Check if the environment variable is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <ENV>"
    exit 1
fi

ENV=$1

# Run the installation scripts
./scripts/linux/install-cert-manager
./scripts/linux/install-linkerd "$ENV"
./scripts/linux/install-kafka "$ENV"
