#!/bin/bash

# Function to check if a command is available
check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo "$1 is not installed or not in your PATH."
        exit 1
    else
        echo "$1 is available."
    fi
}

# Debugging statements
echo "Checking commands..."

# Verify the following
check_command "dotenv"
check_command "docker"
check_command "kubectl"
check_command "terraform"
check_command "helm"
check_command "npx"
check_command "jq"
check_command "linkerd"

echo "All required commands are available."
echo "Script execution completed."
