#!/bin/bash

# Loop over each found .env.vault file
find . -name ".env.vault" | while read -r vault_file; do
  # Change to the directory containing the .env.vault
  dir=$(dirname "$vault_file")
  echo "Building dotenv-vault in directory: $dir"
  
  # Run the build command in that directory
  (cd "$dir" && npx dotenv-vault@latest build)
  
  # Check if the build was successful
  if [ $? -ne 0 ]; then
    echo "Failed to build in directory: $dir"
  else
    echo "Successfully built in directory: $dir"
  fi
done
