#!/bin/bash
# Exit immediately if a command exits with a non-zero status
set -e

helm repo add jetstack https://charts.jetstack.io
helm repo update

# # Use specific kubernetes context
# # Install Cert Manager
helm upgrade \
  --install cert-manager --repo https://charts.jetstack.io cert-manager --namespace cert-manager --create-namespace --version v1.12.0 --set installCRDs=true

