#!/bin/bash
# Exit immediately if a command exits with a non-zero status
set -e

envParam="$1"
# Delete Terraform state files and directory
rm -rf ./iac/terraform/.terraform
rm -f ./iac/terraform/.terraform.lock.hcl
rm -f ./iac/terraform/terraform.tfstate
rm -f ./iac/terraform/terraform.tfstate.backup
