# Dockerfile.consumer

# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the TypeScript files
COPY .env.vault ./
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript files
RUN npx tsc

# Command to run the consumer
CMD ["node", "dist/index.js"]
