#!/bin/bash

# Use the BROKER environment variable, or default to localhost:9092 if not set
BROKER=${BROKER:-"localhost:9092"}

/opt/kafka/bin/kafka-leader-election.sh \
  --bootstrap-server $BROKER \
  --election-type preferred \
  --all-topic-partitions
