
FROM alpine:latest
RUN echo "Hello, World!A"

# Install dependencies (example)
RUN apk add --no-cache bash
# Print Hello, World! to verify the build
RUN echo "Hello, World!"

# Specify the default command to run
CMD ["echo", "This is a more complete Dockerfile"]